###
GET http://localhost:4000/user-api/user

###
GET http://localhost:4000/user-api/users/haradeeps119@gmail.com

###
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "height":184,
    "weight": 70,
    "age": 20,
    "desiredweight":74,
    "gender":"Male",
    "firstName": "Rishi",
    "lastName": "Varma",
    "email": "rishivamra.d@gmail.com",
    "profileImageUrl":"dfgfdgdf",
    "userProducts":[{"title":"dkfkldsj"}],
    "cost":0
}

###
PUT http://localhost:4000/user-api/users/67d679640753b18bead4e780
Content-Type: application/json

{
    "height":182,
    "weight": 71,
    "age": 20,
    "desiredweight":69,
    "gender":"Male",
    "firstName": "Rishi",
    "lastName": "Varma",
    "email": "rishi@gmail.com",
    "profileImageUrl":"dfgfdgdf",
    "userProducts":[{"title":"dkfkldsj"}],
    "cost":0
}

###get all plans
GET http://localhost:4000/plan-api/plan

###get plan by calories
GET http://localhost:4000/plan-api/plan/1600


###create new plan
POST http://localhost:4000/plan-api/plans
Content-Type: application/json

{
    "id":1,
    "calories":1600,
    "veg":{
        "breakfast":["idk"], 
        "lunch":["idk"], 
        "snacks":["idk"], 
        "dinner":["idk"]
    }, 
    "nonveg":{
        "breakfast":["idk"], 
        "lunch":["idk"], 
        "snacks":["idk"], 
        "dinner":["idk"]
    }
}

###get all meals
GET http://localhost:4000/food-api/meal

# /meals?type=Veg&mealType=Lunch&excludeAllergens=Nuts&sortBy=popularityScore

###create meal
POST http://localhost:4000/food-api/meals
Content-Type: application/json

{
  "id":4,
  "name": "Brown Rice",
  "category": ["Grains"],
  "type": ["Vegan", "Vegetarian"],
  "mealType": ["Lunch", "Dinner"],
  "caloriesPer100g": 110,
  "proteinPer100g": 3,
  "carbsPer100g": 23,
  "fatsPer100g": 1
}


###get all products
GET http://localhost:4000/product-api/product

###get product by id
GET http://localhost:4000/product-api/product/67d6ea70fd31443e80d88123

###create product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "img":"https://fakestoreapi.com/img/61sbMiUnoGL.AC_UL640_QL65_ML3.jpg",
    "title":"Solid Gold Petite Micropave",
    "description":"Satisfaction Guaranteed. Return or exchange any order within 30 days.",
    "price":6,
    "id":10
}